# Generated by Django 4.2.1 on 2023-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('no_of_prompts', models.IntegerField()),
                ('prompt1', models.CharField(max_length=1000)),
                ('prompt2', models.CharField(max_length=1000)),
                ('prompt3', models.CharField(max_length=1000)),
                ('prompt4', models.CharField(max_length=1000)),
                ('prompt5', models.CharField(max_length=1000)),
                ('prompt6', models.CharField(max_length=1000)),
                ('prompt7', models.CharField(max_length=1000)),
                ('prompt8', models.CharField(max_length=1000)),
                ('prompt9', models.CharField(max_length=1000)),
                ('prompt10', models.CharField(max_length=1000)),
                ('prompt11', models.CharField(max_length=1000)),
            ],
        ),
    ]
