# Generated by Django 4.2.1 on 2023-05-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0002_remove_prompts_prompt11_prompts_sample_op_input1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='prompt10',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt2',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt3',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt4',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt5',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt6',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt7',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt8',
            field=models.CharField(default='Null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt9',
            field=models.CharField(default='Null', max_length=1000),
        ),
    ]
